n = str(input("digite seu nome completo: ")).strip()
nome = n.split()
print("prazer em te conhecer! {}" .format(n))
print("seu primeiro nome é {}" .format(nome[0]))
print("seu ultimo nome a aparaceu em {}" .format(nome[len(nome)-1]))