numero1 = int(input("escolha um numero"))
print(numero1)
numero2 = int(input("outro"))
print(numero1 + numero2)
print(4 + 5)
print("ola, mundo" , 5)
nome = input("qual o seu nome ?")
idade = input("quantos anos voce tem ?")
peso = input("quanto voce pesa")
print (nome , idade , peso)