p = input("digite algo: ")
print("o tipo primitivo deste valor é: <class '",p.istitle(),"'>")
print("só tem espaços ?",p.isspace())
print("é um número ?", p.isnumeric())
print("é alfabético ?", p.isalpha())
print("está em maisculas ?", p.isupper())
print("está em minusculo ?", p.islower())
print("está capitalizada ?", p.isascii())