n = str(input("qual seu nome? "))
ns = n.split()
print(n.upper())
print(n.lower())
print(len(n.strip()))
print(len(ns[0]))
print('Silva' in n)
c = str(input("qual o nome da sua cidade: "))
print(c[:5] == 'Santo')