p = input("digite algo: ")
print("o tipo primitivo deste valor é: ", type(p))
print("só tem espaços ?",p.isspace())
print("é um número ?", p.isnumeric())
print("é alfabético ?", p.isalpha())
print("é alfanumérico ?", p.isalnum())
print("está em maisculas ?", p.isupper())
print("está em minusculo ?", p.islower())
print("está capitalizada ?", p.istitle())